# Generated by Django 4.1.7 on 2023-03-16 13:33
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Buyer', 'Buyer')], default=float, max_length=300),
            preserve_default=False,
        ),
    ]
