# Generated by Django 4.1.7 on 2023-03-16 15:58

from django.db import migrations
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_rename_adrees_profile_adress_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='staff',
            new_name='username',
        ),
    ]
