# Generated by Django 4.1.7 on 2023-03-16 18:29

from django.db import migrations
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
