# Generated by Django 4.1.7 on 2023-03-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adress',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
